backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "coin-content"
    preview: false
    label: "coin-content"
    folder: "contents/coin-content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title",widget: "string"}
      - { label: "Price" , name: "price" ,widget: "string"}
      - { label: "image" , name: "feature-image" ,widget: "image"}
      - { label: "body" , name: "body" ,widget: "markdown"}

